/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function cat(path: string): string
export function fibonacci(n: number): number
export type RSWatcher = RsWatcher
export class RsWatcher {
  name: string
  kind: number
  constructor(name: string, kind: number)
  changeName(name: string): void
}
